name: Test
on:
  pull_request:
jobs:
  build:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          show-progress: false
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        name: Configure PNPM
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Code Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test:unit